#!/bin/bash
# Wait for the study to finish, then commit and push the results.
#
# The pipeline produces REPORT.md and IMPLEMENTATION_AUDIT.md but stops there.
# /workspace is not a volume on this box -- a recycle takes everything -- so the
# results are not safe until they are on the remote.
#
# Pushes whatever exists once the study completes, or after DEADLINE_HOURS
# either way, so a stalled sweep still leaves the work recoverable.
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:$PATH
ROOT=/workspace/prism-exp
BASE=$ROOT/exp/results/paper-faithful-v4
LOG=/workspace/logs/prism_v4_push.log
EXPECTED=${V4_EXPECTED_RUNS:-27}
DEADLINE_HOURS=${DEADLINE_HOURS:-9}

say() { echo "$(date -Is) $*" >> "$LOG"; }
done_runs() { find "$BASE/raw" -path '*/seed_[0-9]*/DONE' -type f 2>/dev/null | wc -l; }

complete() {
    [ "$(done_runs)" -ge "$EXPECTED" ] || return 1
    [ -s "$BASE/summary.csv" ] && [ -s "$BASE/REPORT.md" ] \
        && [ -s "$BASE/IMPLEMENTATION_AUDIT.md" ]
}

say "waiting for the study (expect $EXPECTED runs, deadline ${DEADLINE_HOURS}h)"
deadline=$(( $(date +%s) + DEADLINE_HOURS * 3600 ))
while ! complete; do
    [ "$(date +%s)" -ge "$deadline" ] && { say "deadline reached at $(done_runs)/$EXPECTED"; break; }
    sleep 120
done
say "proceeding with $(done_runs)/$EXPECTED runs complete"

cd "$ROOT" || exit 1
# Regenerate from whatever is on disk, so a deadline push still carries a report
# that matches the data rather than a stale one.
source exp/scripts/env.sh >/dev/null 2>&1
python3 exp/scripts/collect_v4_metrics.py --base "$BASE" >> "$LOG" 2>&1
python3 exp/scripts/build_report_v4.py   --base "$BASE" >> "$LOG" 2>&1

git add -A exp/results/paper-faithful-v4 exp/workloads/paper-faithful-v4 2>/dev/null
if git diff --cached --quiet; then
    say "nothing to commit"
else
    git commit -q -m "results: paper-faithful v4 ($(done_runs)/$EXPECTED runs)

Microbenchmarks, TP=2 validation, and the end-to-end sweep across the released
prototype, v3 and v4 on one fixed 2xA100 pair. Raw per-request, per-migration,
per-scheduling-cycle and per-GPU-sample data is kept alongside the summaries;
REPORT.md and IMPLEMENTATION_AUDIT.md are generated from it.

Generated by exp/scripts/finalize_and_push.sh." >> "$LOG" 2>&1
    say "committed"
fi

for attempt in 1 2 3; do
    if git push origin exp/paper-faithful-v4 >> "$LOG" 2>&1; then
        say "pushed (attempt $attempt)"; break
    fi
    say "push failed, retry $attempt"; sleep 60
done
say "finalizer done"
