[program:prism_v5_2]
environment=PROC_NAME="%(program_name)s",CUDA_VISIBLE_DEVICES="0,1"
command=/workspace/prism-exp/exp/scripts/watchdog_v5_2.sh
directory=/workspace/prism-exp
autostart=false
autorestart=unexpected
startsecs=10
stopwaitsecs=90
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
